[workspace]
members = ["core/*", "game/*", "graphics"]

[workspace.dependencies]
env_logger = "0.10"
glutin = "0.32"
glutin-winit = "0.4"
syn = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
quote = "1.0"
winit = { version = "0.29", features = ["rwh_05"] }
wgpu = "24"
